import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import firebase from '../../firebase/clientApp.js';

// importing from
import ChargerMap from './ChargerMap/ChargerMap.js';
import Timer from '../../components/timer.js';
import Footer from './footer.js';

export default function Home() {
  return (
    <>
      <Head>
        <title>Charge and Tarry</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main}`} style={{paddingBottom:'0px'}}>
        <ChargerMap/>
        <div>
          <Timer />
        </div>
      </main>
      <Footer/>
    </>
  )
}
